In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
other_path = "https://raw.githubusercontent.com/carlosjara/eda_icesi/main/Notebooks/DataSet/SABERTYT20162.csv"
df = pd.read_csv(other_path,encoding = 'latin',delimiter=';',na_values=' ')

C:\Users\CARLOS\AppData\Local\Temp\ipykernel_27668\2800842167.py:2: DtypeWarning: Columns (11,12,14,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(other_path,encoding = 'latin',delimiter=';',na_values=' ')

In [3]:
df.shape

(53040, 104)

## Ejercicio 1

**Vea las últimas 10 filas del** ***dataframe*** **"df".** Ingrese sus líneas de código a continuación:

In [4]:
df.tail(10)

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_ESTADOCIVIL,ESTU_TIENE_ETNIA,ESTU_ETNIA,...,MOD_INGLES_DESEM,MOD_INGLES_PNAL,MOD_INGLES_PGREF,MOD_COMUNI_ESCRITA_PUNT,MOD_COMUNI_ESCRITA_DESEM,MOD_COMUNI_ESCRITA_PNAL,MOD_COMUNI_ESCRITA_PGREF,ESTU_ESTADO,INSE,NSE
53030,CC,1 COLOMBIA,F,23/09/1992,20164,EK201640038187,ESTUDIANTE,CASADO,NO,NaN,...,A1-,20,12,104.0,3.0,60.0,60.0,PUBLICAR,"49,44874434",NSE2
53031,CC,1 COLOMBIA,F,8/08/1993,20164,EK201640028017,ESTUDIANTE,SOLTERO,NO,NaN,...,A1-,16,20,104.0,3.0,56.0,57.0,PUBLICAR,"43,10046976",NSE1
53032,CC,1 COLOMBIA,M,14/10/1981,20164,EK201640008378,ESTUDIANTE,CASADO,NO,NaN,...,A1,27,33,88.0,2.0,31.0,32.0,PUBLICAR,"55,88202537",NSE3
53033,CC,1 COLOMBIA,F,9/08/1986,20164,EK201640024984,ESTUDIANTE,SOLTERO,NO,NaN,...,A1,59,59,79.0,1.0,17.0,17.0,PUBLICAR,"34,65458932",NSE1
53034,CC,1 COLOMBIA,M,10/08/1995,20164,EK201640017927,ESTUDIANTE,SOLTERO,NO,NaN,...,B1,91,77,79.0,1.0,17.0,18.0,PUBLICAR,"58,50795831",NSE3
53035,CC,1 COLOMBIA,M,22/01/1992,20164,EK201640005823,ESTUDIANTE,SOLTERO,NO,NaN,...,A1,38,56,104.0,3.0,57.0,63.0,PUBLICAR,"45,34484192",NSE1
53036,CC,1 COLOMBIA,M,7/07/1992,20164,EK201640005164,ESTUDIANTE,SOLTERO,NO,NaN,...,A1,48,68,75.0,1.0,12.0,15.0,PUBLICAR,"39,95548887",NSE1
53037,CC,1 COLOMBIA,M,7/09/1988,20164,EK201640001818,ESTUDIANTE,UNIÓN LIBRE,NO,NaN,...,A1,31,39,60.0,1.0,2.0,2.0,PUBLICAR,"60,76679974",NSE4
53038,CC,1 COLOMBIA,F,2/02/1994,20164,EK201640011583,ESTUDIANTE,SOLTERO,NO,NaN,...,A1,53,63,122.0,4.0,88.0,89.0,PUBLICAR,"69,01629674",NSE4
53039,CC,1 COLOMBIA,M,15/02/1988,20164,EK201640024848,ESTUDIANTE,SOLTERO,NO,NaN,...,A1-,3,3,118.0,3.0,80.0,80.0,PUBLICAR,"41,91417628",NSE1

In [5]:
other_path = "https://raw.githubusercontent.com/lvmeninnovations/datasets/main/crispdm/auto.csv"
df = pd.read_csv(other_path,na_values=None)

In [6]:
df.shape

(204, 26)

In [7]:
df.tail(10)

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
194,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
195,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
196,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
197,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
198,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [8]:
# Crear la lista de nombres para el encabezado
headers = ["factor-riesgo","perdida-promedio-anual","fabricante","tipo-combustible","aspiracion", "num-puertas","estilo-carroceria",
         "traccion","ubicacion-motor","distancia-entre-ejes", "longitud","anchura","altura","peso-vacio","tipo-motor",
         "num-cilindros", "tamano-motor","sistema-combustible","calibre","carrera","relacion-compresion","caballos-fuerza",
         "pico-rpm","millas_por_galon_ciudad","millas_por_galon_carretera","precio"]
df.columns = headers
df.head(10)

,factor-riesgo,perdida-promedio-anual,fabricante,tipo-combustible,aspiracion,num-puertas,estilo-carroceria,traccion,ubicacion-motor,distancia-entre-ejes,...,tamano-motor,sistema-combustible,calibre,carrera,relacion-compresion,caballos-fuerza,pico-rpm,millas_por_galon_ciudad,millas_por_galon_carretera,precio
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430

In [9]:
df.columns

Index(['factor-riesgo', 'perdida-promedio-anual', 'fabricante',
       'tipo-combustible', 'aspiracion', 'num-puertas', 'estilo-carroceria',
       'traccion', 'ubicacion-motor', 'distancia-entre-ejes', 'longitud',
       'anchura', 'altura', 'peso-vacio', 'tipo-motor', 'num-cilindros',
       'tamano-motor', 'sistema-combustible', 'calibre', 'carrera',
       'relacion-compresion', 'caballos-fuerza', 'pico-rpm',
       'millas_por_galon_ciudad', 'millas_por_galon_carretera', 'precio'],
      dtype='object')

In [11]:
#from google.colab import files
df.to_csv("automobile.csv", index=False)
#files.download("automobile.csv")

También podemos leer y guardar otros tipos de formatos utilizando funciones similares a **`pd.read_csv()`** y **`df.to_csv()`**. La siguiente tabla muestra una lista de funciones que le pueden servir:


| Data Formate  | Read           | Save             |
| ------------- |:--------------:| ----------------:|
| csv           | `pd.read_csv()`  |`df.to_csv()`     |
| json          | `pd.read_json()` |`df.to_json()`    |
| excel         | `pd.read_excel()`|`df.to_excel()`   |
| hdf           | `pd.read_hdf()`  |`df.to_hdf()`     |
| sql           | `pd.read_sql()`  |`df.to_sql()`     |
| ...           |   ...          |       ...        |